import { Fragment } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import Aside from '../components/layouts/aside/aside.component';
import Main from '../components/layouts/main/main.component';
import Nav from '../components/layouts/nav/nav.component';

const Home: NextPage = () =>
{
    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Aside />
            <Main />
            <Nav />
        </Fragment>
    );
};

export default Home;
