import { Fragment } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import Main from '../components/layouts/main/main.component';

const Home: NextPage = () =>
{
    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
s
            </Main>
        </Fragment>
    );
};

export default Home;
